executor:
  name: nodejs
  options:
    entry: main.js
inputs_def:
  - handle: array
    description: "%array%"
    json_schema:
      type: array
outputs_def:
  - handle: item
    description: "%each-array-item%"
    json_schema:
      {}
  - handle: index
    description: "%item-index%"
    json_schema:
      type: integer
  - handle: length
    description: "%array-length%"
    json_schema:
      type: integer
title: "%each%"
additional_inputs: false
description: "%each-description%"
